<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
    
class Ref_objective extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Ref_objective_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
	    $this->load->library('uuid');
    }

    public function index()
    {
        $this->template->load('template','Ref_objective/index');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Ref_objective_model->json();
    }

    public function save() 
    {
        $mode = $this->input->post('mode',TRUE);
        $id = $this->input->post('id_objective',TRUE);
        $dt = new DateTime();

        if ($mode=="insert"){
            $data = array(
            'id_objective' => $this->input->post('id_objecitive',TRUE),
            'objective' => $this->input->post('objective',TRUE),
            'uuid' => $this->uuid->v4(),
            'flag' => '0',
            'user_created' => $this->session->userdata('id_users'),
            'date_created' => $dt->format('Y-m-d H:i:s'),
            );
 
            $this->Ref_objective_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');    
        }
        else if ($mode=="edit"){
            $data = array(
            'id_objective' => $this->input->post('id_objective',TRUE),
            'objective' => $this->input->post('objective',TRUE),
            'uuid' => $this->uuid->v4(),
            'flag' => '0',
            'user_updated' => $this->session->userdata('id_users'),
            'date_updated' => $dt->format('Y-m-d H:i:s'),
            );

            $this->Ref_objective_model->update($id, $data);
            $this->session->set_flashdata('message', 'Create Record Success');    
        }

        redirect(site_url("Ref_objective"));
    }

    public function delete($id) 
    {
        $row = $this->Ref_objective_model->get_by_id($id);
        $data = array(
            'flag' => 1,
            );

        if ($row) {
            $this->Ref_objective_model->update($id, $data);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('Ref_objective'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('Ref_objective'));
        }
    }

    public function valid_bs() 
    {
        $id = $this->input->get('id1');
        $data = $this->Ref_objective_model->validate1($id);
        header('Content-Type: application/json');
        echo json_encode($data);
    }


    public function excel() {
    
        $spreadsheet = new Spreadsheet();    
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1', "ID"); 
        $sheet->setCellValue('B1', "Objective");

        $ref_objective = $this->Ref_objective_model->get_ref_objective();
    
        $numrow = 2;
        foreach($ref_objective as $data){ 
            if (property_exists($data, 'id_objective')) {
                $sheet->setCellValue('A'.$numrow, $data->id_objective);
            } else {
                $sheet->setCellValue('A'.$numrow, '');
            }
            if (property_exists($data, 'objective')) {
                $sheet->setCellValue('B'.$numrow, $data->objective);
            } else {
                $sheet->setCellValue('B'.$numrow, '');
            }

            $numrow++;
        }

        // Set header untuk file excel
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="Report_ref_objective.xlsx"');
        header('Cache-Control: max-age=0');

        // Tampilkan file excel
        $writer = new Xlsx($spreadsheet);
        $writer->save('php://output');
    }
}

/* End of file Ref_destination.php */
/* Location: ./application/controllers/Ref_destination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-14 03:38:42 */
/* http://harviacode.com */