<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Freezer_out_model extends CI_Model
{

    public $table = 'freezer_out';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('freezer_out.id, freezer_out.date_out, freezer_out.time_out, ref_person.initial,  
                                    freezer_out.barcode_sample, freezer_out.barcode_tube, freezer_out.comments, 
                                    freezer_out.id_person');
        $this->datatables->from('freezer_out');
        $this->datatables->join('ref_person', 'freezer_out.id_person=ref_person.id_person', 'left');
        $this->datatables->where('freezer_out.flag', '0');
        $lvl = $this->session->userdata('id_user_level');
        if ($lvl == 4){
            $this->datatables->add_column('action', '', 'id');
        }
        else if (($lvl == 2) | ($lvl == 3)){
            $this->datatables->add_column('action', '<button type="button" class="btn_edit btn btn-info btn-sm" aria-hidden="true"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Update</button>', 'id');
        }
        else {
            $this->datatables->add_column('action', '<button type="button" class="btn_edit btn btn-info btn-sm" aria-hidden="true"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Update</button>'." 
                ".anchor(site_url('freezer_out/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Confirm deleting sample : $1 ?\')"'), 'id');
        }
        return $this->datatables->generate();
    }

    function get_all()
    {
      $this->db->select('freezer_out.id, freezer_out.date_out, ref_person.initial, freezer_out.barcode_sample, 
            freezer_out.barcode_tube, freezer_out.comments, 
            freezer_out.id_person');
      // $this->db->from('freezer_out');
      $this->db->join('ref_person', 'freezer_out.id_person=ref_person.id_person', 'left');
      $this->db->where('freezer_out.flag', '0');
      $this->db->order_by('freezer_out.date_out, freezer_out.id', 'ASC');
      return $this->db->get('freezer_out')->result();
    }

    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        // $this->db->where('lab', $this->session->userdata('lab'));
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    // function delete($id_user, $data)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->update($this->table, $data);
    // }

    // function delete($id)
    // {
        // $this->db->where($this->id, $id);
        // $this->db->delete($this->table);
    // }

    function getLabtech(){
        $response = array();
        $this->db->select('*');
        $q = $this->db->get('ref_person');
        $response = $q->result_array();
    
        return $response;
      }


    function validate1($id){
      $this->db->where('barcode_tube', $id);
      $q = $this->db->get('freezer_in');
      $response = $q->result_array();
      return $response;
      // return $this->db->get('ref_location_80')->row();
    }

}

/* End of file Tbl_delivery_model.php */
/* Location: ./application/models/Tbl_delivery_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-14 03:38:42 */
/* http://harviacode.com */