<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rep_campympn_model extends CI_Model
{

    public $table = 'sample_reception';
    public $id = 'id_project';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.id_project, a.id_client_sample, a.date_arrival, c.realname, a.flag');
        $this->datatables->from('sample_reception a');
        $this->datatables->join('campy_biosolids b', 'a.id_one_water_sample = b.id_one_water_sample');
        $this->datatables->join('ref_person c', 'b.id_person = c.id_person', 'left');
        $lvl = $this->session->userdata('id_user_level');
        $this->datatables->add_column('action', anchor(site_url('Rep_campympn/read/$1'),'<i class="fa fa-print" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm')), 'id_project');
        return $this->datatables->generate();
    }


    function get_rep($id)
    {
        $q = $this->db->query('SELECT a.id_project, a.id_client_sample, a.date_arrival, c.realname, d.sampletype, a.date_collected, a.time_collected,
        e.testing_type, b.sample_wetweight, b.elution_volume
        FROM sample_reception a
        JOIN campy_biosolids b ON a.id_one_water_sample = b.id_one_water_sample
        LEFT JOIN ref_person c ON b.id_person = c.id_person
        LEFT JOIN ref_sampletype d ON a.id_sampletype= d.id_sampletype
        LEFT JOIN (SELECT x.id_project, GROUP_CONCAT(y.testing_type) AS testing_type
        FROM sample_reception_sample x
        LEFT JOIN ref_testing y ON x.id_testing_type=y.id_testing_type
        GROUP BY x.id_project) e ON a.id_project = e.id_project
        WHERE a.id_project="'.$id.'"
        AND a.flag = 0 
        ');        
        $response = $q->row();
        return $response;
      }


      function get_repdet($id)
      {
          $q = $this->db->query('SELECT * FROM obj2b_spectro_crm_det
          WHERE flag = 0
          AND id_spec="'.$id.'"');        
          $response = $q->row();
          return $response;
        }

        
    // function get_by_id_detail($id)
    // {
    //     $this->db->where('id_delivery_det', $id);
    //     return $this->db->get('tbl_delivery_det')->row();
    // }

    // get total rows
    // function total_rows($q = NULL) {
    //     $this->db->like('id_delivery', $q);
	// $this->db->or_like('date_delivery', $q);
	// $this->db->or_like('delivery_number', $q);
	// $this->db->or_like('customer_name', $q);
	// $this->db->or_like('city', $q);
	// $this->db->or_like('phone', $q);
	// $this->db->or_like('notes', $q);
	// $this->db->from($this->table);
    //     return $this->db->count_all_results();
    // }

    // get data with limit and search
    // function get_limit_data($limit, $start = 0, $q = NULL) {
    //     $this->db->order_by($this->id, $this->order);
    //     $this->db->like('id_delivery', $q);
	// $this->db->or_like('date_delivery', $q);
	// $this->db->or_like('delivery_number', $q);
	// $this->db->or_like('customer_name', $q);
	// $this->db->or_like('city', $q);
	// $this->db->or_like('phone', $q);
	// $this->db->or_like('notes', $q);
	// $this->db->limit($limit, $start);
    //     return $this->db->get($this->table)->result();
    // }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_det($data)
    {
        $this->db->insert('obj2b_spectro_crm_det', $data);
    }
    
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_det($id, $data)
    {
        $this->db->where('id_dspec', $id);
        $this->db->update('obj2b_spectro_crm_det', $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getLabtech(){
        $response = array();
        $this->db->select('*');
        $this->db->where('position', 'Lab Tech');
        $this->db->where('flag', '0');
        $q = $this->db->get('ref_person');
        $response = $q->result_array();
    
        return $response;
      }

      function validate1($id, $type){
        if($type == 1) {
            $this->db->where('barcode_sample', $id);
        }
        $this->db->where('flag', '0');
        $q = $this->db->get($this->table);
        $response = $q->result_array();
        return $response;
        // return $this->db->get('ref_location_80')->row();
      }
      
}

/* End of file Tbl_delivery_model.php */
/* Location: ./application/models/Tbl_delivery_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-14 03:38:42 */
/* http://harviacode.com */